// Every Ripllo feature route, one method each — generated by apigen from
// backend/openapi.json. Do not edit by hand; regenerate after the API changes.
// Reach them as `client.api.<area><Action>(...)`; each call goes through the client's
// own `apigenRequest` (its sign-in and response envelope).

export interface ApigenTransport {
  apigenRequest(method: string, path: string, query: Record<string, unknown> | undefined, body: unknown): Promise<unknown>;
}

/** All 208 feature routes of the Ripllo API. */
export class GeneratedApi {
  constructor(private readonly client: ApigenTransport) {}

  private call(method: string, path: string, query: Record<string, unknown>, body: unknown): Promise<unknown> {
    const q = Object.fromEntries(Object.entries(query).filter(([, v]) => v !== undefined && v !== null));
    return this.client.apigenRequest(method, path, Object.keys(q).length ? q : undefined, body);
  }

  /** List config (GET /api/v1/abandoned-cart/config) */
  abandonedCartConfig(): Promise<unknown> {
    return this.call("GET", `/api/v1/abandoned-cart/config`, {}, undefined);
  }

  /** Create a reminder (POST /api/v1/abandoned-cart/reminders) */
  abandonedCartCreateReminders(input: { "accountId": string; "customerId": string; "cartId": string; "email": string; "cartSnapshot"?: unknown; "valueAtSend": number; "currencyAtSend": string; "discountCodeId"?: string; "externalSource"?: string; "externalRef"?: string }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/abandoned-cart/reminders`, query, all);
  }

  /** Create a suppression (POST /api/v1/abandoned-cart/suppressions) */
  abandonedCartCreateSuppressions(input: { "email": string }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/abandoned-cart/suppressions`, query, all);
  }

  /** Delete a suppression (DELETE /api/v1/abandoned-cart/suppressions/{email}) */
  abandonedCartDeleteSuppressions(email: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/abandoned-cart/suppressions/${encodeURIComponent(email)}`, {}, undefined);
  }

  /** Create a recover (POST /api/v1/abandoned-cart/recover) */
  abandonedCartRecover(input: { "accountId": string; "customerId": string; "checkoutSessionId": string; "completedAt"?: string }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/abandoned-cart/recover`, query, all);
  }

  /** List reminders (GET /api/v1/abandoned-cart/reminders) */
  abandonedCartReminders(input?: { "limit"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["limit"] = all["limit"]; delete all["limit"];
    return this.call("GET", `/api/v1/abandoned-cart/reminders`, query, undefined);
  }

  /** List stats (GET /api/v1/abandoned-cart/stats) */
  abandonedCartStats(input?: { "windowDays"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["windowDays"] = all["windowDays"]; delete all["windowDays"];
    return this.call("GET", `/api/v1/abandoned-cart/stats`, query, undefined);
  }

  /** The merchant-facing surface for opted-out buyers. (GET /api/v1/abandoned-cart/suppressions) */
  abandonedCartSuppressions(input?: { "limit"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["limit"] = all["limit"]; delete all["limit"];
    return this.call("GET", `/api/v1/abandoned-cart/suppressions`, query, undefined);
  }

  /** List unsubscribe (GET /api/v1/abandoned-cart/unsubscribe) */
  abandonedCartUnsubscribe(input?: { "accountId"?: unknown; "email"?: unknown; "token"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["accountId"] = all["accountId"]; delete all["accountId"];
    query["email"] = all["email"]; delete all["email"];
    query["token"] = all["token"]; delete all["token"];
    return this.call("GET", `/api/v1/abandoned-cart/unsubscribe`, query, undefined);
  }

  /** Update config (PATCH /api/v1/abandoned-cart/config) */
  abandonedCartUpdateConfig(input?: { "enabled"?: boolean; "delayHours"?: number; "emailSubject"?: string; "emailPreview"?: string; "discountCodeId"?: string; "marketingCampaignId"?: string }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/abandoned-cart/config`, query, all);
  }

  /** List affiliators (GET /api/v1/affiliates/affiliators) */
  affiliatesAffiliators(input?: { "channel"?: string; "country"?: string; "cursor"?: string; "limit"?: number }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["channel"] = all["channel"]; delete all["channel"];
    query["country"] = all["country"]; delete all["country"];
    query["cursor"] = all["cursor"]; delete all["cursor"];
    query["limit"] = all["limit"]; delete all["limit"];
    return this.call("GET", `/api/v1/affiliates/affiliators`, query, undefined);
  }

  /** Get an affiliator (GET /api/v1/affiliates/affiliators/{handle}) */
  affiliatesAffiliators2(handle: string): Promise<unknown> {
    return this.call("GET", `/api/v1/affiliates/affiliators/${encodeURIComponent(handle)}`, {}, undefined);
  }

  /** List commissions (GET /api/v1/affiliates/me/commissions) */
  affiliatesMeCommissions(input?: { "limit"?: unknown; "status"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["limit"] = all["limit"]; delete all["limit"];
    query["status"] = all["status"]; delete all["status"];
    return this.call("GET", `/api/v1/affiliates/me/commissions`, query, undefined);
  }

  /** List enrollments (GET /api/v1/affiliates/me/enrollments) */
  affiliatesMeEnrollments(): Promise<unknown> {
    return this.call("GET", `/api/v1/affiliates/me/enrollments`, {}, undefined);
  }

  /** List programs (GET /api/v1/affiliates/programs) */
  affiliatesPrograms(input?: { "cursor"?: unknown; "limit"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["cursor"] = all["cursor"]; delete all["cursor"];
    query["limit"] = all["limit"]; delete all["limit"];
    return this.call("GET", `/api/v1/affiliates/programs`, query, undefined);
  }

  /** Get a program (GET /api/v1/affiliates/programs/{id}) */
  affiliatesPrograms2(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/affiliates/programs/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** Enroll a program (POST /api/v1/affiliates/programs/{id}/enroll) */
  affiliatesProgramsEnroll(id: string): Promise<unknown> {
    return this.call("POST", `/api/v1/affiliates/programs/${encodeURIComponent(id)}/enroll`, {}, undefined);
  }

  /** Create an affiliator profile (POST /api/v1/affiliator-profile) */
  affiliatorProfileCreate(input: { "handle": string; "displayName": string; "bio"?: string; "avatarKey"?: string; "channels"?: unknown[]; "country"?: string; "payoutMethod"?: Record<string, unknown> }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/affiliator-profile`, query, all);
  }

  /** List me (GET /api/v1/affiliator-profile/me) */
  affiliatorProfileMe(): Promise<unknown> {
    return this.call("GET", `/api/v1/affiliator-profile/me`, {}, undefined);
  }

  /** Update me (PATCH /api/v1/affiliator-profile/me) */
  affiliatorProfileUpdateMe(input?: { "handle"?: string; "displayName"?: string; "bio"?: string; "avatarKey"?: string; "channels"?: unknown[]; "country"?: string; "payoutMethod"?: Record<string, unknown> }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/affiliator-profile/me`, query, all);
  }

  /** Create an api key (POST /api/v1/api-keys) */
  apiKeysCreate(input: { "name": string; "scopes"?: unknown[] }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/api-keys`, query, all);
  }

  /** List api keys (GET /api/v1/api-keys) */
  apiKeysList(): Promise<unknown> {
    return this.call("GET", `/api/v1/api-keys`, {}, undefined);
  }

  /** Revoke an api key (POST /api/v1/api-keys/{id}/revoke) */
  apiKeysRevoke(id: string): Promise<unknown> {
    return this.call("POST", `/api/v1/api-keys/${encodeURIComponent(id)}/revoke`, {}, undefined);
  }

  /** Create an audience segment (POST /api/v1/audience-segments) */
  audienceSegmentsCreate(input: { "name": string; "description"?: string; "filter": Record<string, unknown> }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/audience-segments`, query, all);
  }

  /** Preview an audience segment (POST /api/v1/audience-segments/{id}/preview) */
  audienceSegmentsCreatePreview(id: string): Promise<unknown> {
    return this.call("POST", `/api/v1/audience-segments/${encodeURIComponent(id)}/preview`, {}, undefined);
  }

  /** Ad-hoc resolve — accepts a raw filter without saving. (POST /api/v1/audience-segments/preview) */
  audienceSegmentsCreatePreview2(input: { "match": "all" | "any"; "rules": unknown[] }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/audience-segments/preview`, query, all);
  }

  /** Delete an audience segment (DELETE /api/v1/audience-segments/{id}) */
  audienceSegmentsDelete(id: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/audience-segments/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** Get an audience segment (GET /api/v1/audience-segments/{id}) */
  audienceSegmentsGet(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/audience-segments/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List audience segments (GET /api/v1/audience-segments) */
  audienceSegmentsList(): Promise<unknown> {
    return this.call("GET", `/api/v1/audience-segments`, {}, undefined);
  }

  /** Update an audience segment (PATCH /api/v1/audience-segments/{id}) */
  audienceSegmentsUpdate(id: string, input?: { "name"?: string; "description"?: string; "filter"?: Record<string, unknown> }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/audience-segments/${encodeURIComponent(id)}`, query, all);
  }

  /** List audit log (GET /api/v1/audit-log) */
  auditLogList(input?: { "action"?: unknown; "limit"?: unknown; "target_type"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["action"] = all["action"]; delete all["action"];
    query["limit"] = all["limit"]; delete all["limit"];
    query["target_type"] = all["target_type"]; delete all["target_type"];
    return this.call("GET", `/api/v1/audit-log`, query, undefined);
  }

  /** Create a cancel (POST /api/v1/billing/cancel) */
  billingCancel(): Promise<unknown> {
    return this.call("POST", `/api/v1/billing/cancel`, {}, undefined);
  }

  /** Create a checkout (POST /api/v1/billing/checkout) */
  billingCheckout(input: { "plan": "STARTER" | "GROWTH" | "SCALE"; "email"?: string; "name"?: string }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/billing/checkout`, query, all);
  }

  /** List invoices (GET /api/v1/billing/invoices) */
  billingInvoices(input?: { "cursor"?: unknown; "limit"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["cursor"] = all["cursor"]; delete all["cursor"];
    query["limit"] = all["limit"]; delete all["limit"];
    return this.call("GET", `/api/v1/billing/invoices`, query, undefined);
  }

  /** List plan (GET /api/v1/billing/plan) */
  billingPlan(): Promise<unknown> {
    return this.call("GET", `/api/v1/billing/plan`, {}, undefined);
  }

  /** Public, no auth. (GET /api/v1/billing/plans) */
  billingPlans(): Promise<unknown> {
    return this.call("GET", `/api/v1/billing/plans`, {}, undefined);
  }

  /** List subscription (GET /api/v1/billing/subscription) */
  billingSubscription(): Promise<unknown> {
    return this.call("GET", `/api/v1/billing/subscription`, {}, undefined);
  }

  /** List usage (GET /api/v1/billing/usage) */
  billingUsage(): Promise<unknown> {
    return this.call("GET", `/api/v1/billing/usage`, {}, undefined);
  }

  /** Create a blog (POST /api/v1/blog) */
  blogCreate(input: { "slug": string; "title": string; "excerpt"?: string; "body": string; "coverImage"?: string; "status"?: "draft" | "published"; "publishedAt"?: string; "authorName"?: string; "tags"?: unknown[]; "metaTitle"?: string; "metaDescription"?: string; "marketingCampaignId"?: string }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/blog`, query, all);
  }

  /** Delete a blog (DELETE /api/v1/blog/{id}) */
  blogDelete(id: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/blog/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** Get a blog (GET /api/v1/blog/{id}) */
  blogGet(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/blog/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List blog (GET /api/v1/blog) */
  blogList(input?: { "status"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["status"] = all["status"]; delete all["status"];
    return this.call("GET", `/api/v1/blog`, query, undefined);
  }

  /** Public storefront read — list published posts. (GET /api/v1/blog/public/{accountId}) */
  blogPublic(accountId: string): Promise<unknown> {
    return this.call("GET", `/api/v1/blog/public/${encodeURIComponent(accountId)}`, {}, undefined);
  }

  /** Get a public (GET /api/v1/blog/public/{accountId}/{slug}) */
  blogPublic2(accountId: string, slug: string): Promise<unknown> {
    return this.call("GET", `/api/v1/blog/public/${encodeURIComponent(accountId)}/${encodeURIComponent(slug)}`, {}, undefined);
  }

  /** Update a blog (PATCH /api/v1/blog/{id}) */
  blogUpdate(id: string, input?: { "slug"?: string; "title"?: string; "excerpt"?: string; "body"?: string; "coverImage"?: string; "status"?: "draft" | "published"; "publishedAt"?: string; "authorName"?: string; "tags"?: unknown[]; "metaTitle"?: string; "metaDescription"?: string; "marketingCampaignId"?: string }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/blog/${encodeURIComponent(id)}`, query, all);
  }

  /** Cancel a broadcast (POST /api/v1/broadcasts/{id}/cancel) */
  broadcastsCancel(id: string): Promise<unknown> {
    return this.call("POST", `/api/v1/broadcasts/${encodeURIComponent(id)}/cancel`, {}, undefined);
  }

  /** Create a broadcast (POST /api/v1/broadcasts) */
  broadcastsCreate(input: { "name": string; "description"?: string; "providers": unknown[]; "content"?: Record<string, unknown>; "audience"?: Record<string, unknown>; "scheduledAt"?: string; "marketingCampaignId"?: string }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/broadcasts`, query, all);
  }

  /** Create a template (POST /api/v1/broadcasts/templates) */
  broadcastsCreateTemplates(input: { "name": string; "description"?: string; "providers"?: unknown[]; "content"?: Record<string, unknown>; "blocks"?: Record<string, unknown> }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/broadcasts/templates`, query, all);
  }

  /** Delete a template (DELETE /api/v1/broadcasts/templates/{tid}) */
  broadcastsDeleteTemplates(tid: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/broadcasts/templates/${encodeURIComponent(tid)}`, {}, undefined);
  }

  /** Get a broadcast (GET /api/v1/broadcasts/{id}) */
  broadcastsGet(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/broadcasts/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List broadcasts (GET /api/v1/broadcasts) */
  broadcastsList(): Promise<unknown> {
    return this.call("GET", `/api/v1/broadcasts`, {}, undefined);
  }

  /** Fan out: resolve audience → contacts → per (contact × provider) → MarketingMessage rows in `queued`. (POST /api/v1/broadcasts/{id}/send) */
  broadcastsSend(id: string): Promise<unknown> {
    return this.call("POST", `/api/v1/broadcasts/${encodeURIComponent(id)}/send`, {}, undefined);
  }

  /** Send a single test message — bypasses audience resolution. (POST /api/v1/broadcasts/{id}/send-test) */
  broadcastsSendTest(id: string, input?: { "provider"?: unknown; "recipient"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/broadcasts/${encodeURIComponent(id)}/send-test`, query, all);
  }

  /** List templates (GET /api/v1/broadcasts/templates) */
  broadcastsTemplates(): Promise<unknown> {
    return this.call("GET", `/api/v1/broadcasts/templates`, {}, undefined);
  }

  /** Create a compile (POST /api/v1/broadcasts/templates/compile) */
  broadcastsTemplatesCompile(input: { "subject": string; "preheader": string; "accentColor"?: string; "blocks": unknown[] }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/broadcasts/templates/compile`, query, all);
  }

  /** Update a broadcast (PATCH /api/v1/broadcasts/{id}) */
  broadcastsUpdate(id: string, input?: { "name"?: string; "description"?: string; "providers"?: unknown[]; "content"?: Record<string, unknown>; "audience"?: Record<string, unknown>; "scheduledAt"?: string; "marketingCampaignId"?: string }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/broadcasts/${encodeURIComponent(id)}`, query, all);
  }

  /** Server-side compile of a blocks doc → HTML/text. (PATCH /api/v1/broadcasts/templates/{tid}) */
  broadcastsUpdateTemplates(tid: string, input?: { "name"?: string; "description"?: string; "providers"?: unknown[]; "content"?: Record<string, unknown>; "blocks"?: Record<string, unknown> }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/broadcasts/templates/${encodeURIComponent(tid)}`, query, all);
  }

  /** Per-campaign analytics. (GET /api/v1/campaigns/{id}/analytics) */
  campaignsAnalytics(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/campaigns/${encodeURIComponent(id)}/analytics`, {}, undefined);
  }

  /** List applications (GET /api/v1/campaigns/{id}/applications) */
  campaignsApplications(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/campaigns/${encodeURIComponent(id)}/applications`, {}, undefined);
  }

  /** Accept an application (POST /api/v1/campaigns/{id}/applications/{aid}/accept) */
  campaignsApplicationsAccept(id: string, aid: string, input?: { "notes"?: string }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/campaigns/${encodeURIComponent(id)}/applications/${encodeURIComponent(aid)}/accept`, query, all);
  }

  /** Reject an application (POST /api/v1/campaigns/{id}/applications/{aid}/reject) */
  campaignsApplicationsReject(id: string, aid: string, input?: { "notes"?: string }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/campaigns/${encodeURIComponent(id)}/applications/${encodeURIComponent(aid)}/reject`, query, all);
  }

  /** Create a campaign (POST /api/v1/campaigns) */
  campaignsCreate(input: { "name": string; "brief": string; "budgetIdr"?: number; "deliverables"?: unknown[]; "pricingModel"?: "flat" | "cpm" | "hybrid"; "status"?: "draft" | "open" | "closed" | "archived"; "discoveryMode"?: "public" | "invite_only"; "tierFloor"?: "growth" | "scale"; "platformFeeRate"?: number; "startsAt"?: string; "endsAt"?: string; "marketingCampaignId"?: string }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/campaigns`, query, all);
  }

  /** Invitations a campaign (POST /api/v1/campaigns/{id}/invitations) */
  campaignsCreateInvitations(id: string, input: { "creatorId": string; "message"?: string }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/campaigns/${encodeURIComponent(id)}/invitations`, query, all);
  }

  /** Get a campaign (GET /api/v1/campaigns/{id}) */
  campaignsGet(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/campaigns/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** The invitations sent from this brief. (GET /api/v1/campaigns/{id}/invitations) */
  campaignsInvitations(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/campaigns/${encodeURIComponent(id)}/invitations`, {}, undefined);
  }

  /** List campaigns (GET /api/v1/campaigns) */
  campaignsList(input?: { "marketingCampaignId"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["marketingCampaignId"] = all["marketingCampaignId"]; delete all["marketingCampaignId"];
    return this.call("GET", `/api/v1/campaigns`, query, undefined);
  }

  /** Update a campaign (PATCH /api/v1/campaigns/{id}) */
  campaignsUpdate(id: string, input?: { "name"?: string; "brief"?: string; "budgetIdr"?: number; "deliverables"?: unknown[]; "pricingModel"?: "flat" | "cpm" | "hybrid"; "status"?: "draft" | "open" | "closed" | "archived"; "discoveryMode"?: "public" | "invite_only"; "tierFloor"?: "growth" | "scale"; "platformFeeRate"?: number; "startsAt"?: string; "endsAt"?: string; "marketingCampaignId"?: string }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/campaigns/${encodeURIComponent(id)}`, query, all);
  }

  /** Create a channel (POST /api/v1/channels) */
  channelsCreate(input: { "provider": "email_resend" | "email_sendgrid" | "email_mailgun" | "email_postmark" | "email_ses" | "sms_twilio" | "sms_vonage" | "whatsapp_cloud" | "whatsapp_twilio" | "telegram_bot" | "line_business" | "discord_webhook" | "slack_webhook" | "push_onesignal" | "push_fcm" | "meta_business" | "linkedin" | "tiktok_business" | "twitter" | "youtube" | "pinterest" | "threads" | "webhook_generic"; "displayName": string; "externalId"?: string; "credentials": Record<string, unknown>; "config"?: Record<string, unknown>; "scopesGranted"?: unknown[] }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/channels`, query, all);
  }

  /** Delete a channel (DELETE /api/v1/channels/{id}) */
  channelsDelete(id: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/channels/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** DNS records guidance for email channels. (GET /api/v1/channels/{id}/dns-records) */
  channelsDnsRecords(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/channels/${encodeURIComponent(id)}/dns-records`, {}, undefined);
  }

  /** Get a channel (GET /api/v1/channels/{id}) */
  channelsGet(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/channels/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List channels (GET /api/v1/channels) */
  channelsList(): Promise<unknown> {
    return this.call("GET", `/api/v1/channels`, {}, undefined);
  }

  /** Verify a connected channel works by sending a one-shot test message. (POST /api/v1/channels/{id}/test) */
  channelsTest(id: string, input?: { "recipient"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/channels/${encodeURIComponent(id)}/test`, query, all);
  }

  /** Update a channel (PATCH /api/v1/channels/{id}) */
  channelsUpdate(id: string, input?: { "displayName"?: string; "config"?: Record<string, unknown> }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/channels/${encodeURIComponent(id)}`, query, all);
  }

  /** Approve a collaboration (POST /api/v1/collaborations/{id}/approve) */
  collaborationsApprove(id: string): Promise<unknown> {
    return this.call("POST", `/api/v1/collaborations/${encodeURIComponent(id)}/approve`, {}, undefined);
  }

  /** Cancel a collaboration (POST /api/v1/collaborations/{id}/cancel) */
  collaborationsCancel(id: string, input: { "reason": string }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/collaborations/${encodeURIComponent(id)}/cancel`, query, all);
  }

  /** Approve a deliverable (POST /api/v1/collaborations/{id}/deliverables/{did}/approve) */
  collaborationsDeliverablesApprove(id: string, did: string, input?: { "notes"?: string }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/collaborations/${encodeURIComponent(id)}/deliverables/${encodeURIComponent(did)}/approve`, query, all);
  }

  /** Published a deliverable (POST /api/v1/collaborations/{id}/deliverables/{did}/published) */
  collaborationsDeliverablesPublished(id: string, did: string, input: { "publishedUrl": string }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/collaborations/${encodeURIComponent(id)}/deliverables/${encodeURIComponent(did)}/published`, query, all);
  }

  /** Reject a deliverable (POST /api/v1/collaborations/{id}/deliverables/{did}/reject) */
  collaborationsDeliverablesReject(id: string, did: string, input?: { "notes"?: string }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/collaborations/${encodeURIComponent(id)}/deliverables/${encodeURIComponent(did)}/reject`, query, all);
  }

  /** Re-run the watermark pipeline on a deliverable. (POST /api/v1/collaborations/{id}/deliverables/{did}/retry-watermark) */
  collaborationsDeliverablesRetryWatermark(id: string, did: string): Promise<unknown> {
    return this.call("POST", `/api/v1/collaborations/${encodeURIComponent(id)}/deliverables/${encodeURIComponent(did)}/retry-watermark`, {}, undefined);
  }

  /** Upload key a deliverable (POST /api/v1/collaborations/{id}/deliverables/{did}/upload-key) */
  collaborationsDeliverablesUploadKey(id: string, did: string, input: { "originalKey": string }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/collaborations/${encodeURIComponent(id)}/deliverables/${encodeURIComponent(did)}/upload-key`, query, all);
  }

  /** Dispute a collaboration (POST /api/v1/collaborations/{id}/dispute) */
  collaborationsDispute(id: string, input: { "notes": string }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/collaborations/${encodeURIComponent(id)}/dispute`, query, all);
  }

  /** Act on a from application (POST /api/v1/collaborations/from-application/{appId}) */
  collaborationsFromApplication(appId: string, input: { "agreedTotalIdr": number; "merchantEmail": string }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/collaborations/from-application/${encodeURIComponent(appId)}`, query, all);
  }

  /** Get a collaboration (GET /api/v1/collaborations/{id}) */
  collaborationsGet(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/collaborations/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List collaborations (GET /api/v1/collaborations) */
  collaborationsList(input?: { "campaignId"?: unknown; "status"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["campaignId"] = all["campaignId"]; delete all["campaignId"];
    query["status"] = all["status"]; delete all["status"];
    return this.call("GET", `/api/v1/collaborations`, query, undefined);
  }

  /** Create a contact list (POST /api/v1/contact-lists) */
  contactListsCreate(input: { "name": string; "description"?: string }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/contact-lists`, query, all);
  }

  /** Members a contact list (POST /api/v1/contact-lists/{id}/members) */
  contactListsCreateMembers(id: string, input: { "contactIds": unknown[] }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/contact-lists/${encodeURIComponent(id)}/members`, query, all);
  }

  /** Delete a contact list (DELETE /api/v1/contact-lists/{id}) */
  contactListsDelete(id: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/contact-lists/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** Delete a member (DELETE /api/v1/contact-lists/{id}/members/{contactId}) */
  contactListsDeleteMembers(id: string, contactId: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/contact-lists/${encodeURIComponent(id)}/members/${encodeURIComponent(contactId)}`, {}, undefined);
  }

  /** Get a contact list (GET /api/v1/contact-lists/{id}) */
  contactListsGet(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/contact-lists/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List contact lists (GET /api/v1/contact-lists) */
  contactListsList(): Promise<unknown> {
    return this.call("GET", `/api/v1/contact-lists`, {}, undefined);
  }

  /** Create a contact (POST /api/v1/contacts) */
  contactsCreate(input?: { "email"?: string; "phone"?: string; "firstName"?: string; "lastName"?: string; "socialHandles"?: Record<string, unknown>; "subscriptions"?: Record<string, unknown>; "attributes"?: Record<string, unknown>; "source"?: string; "externalRef"?: string }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/contacts`, query, all);
  }

  /** Delete a contact (DELETE /api/v1/contacts/{id}) */
  contactsDelete(id: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/contacts/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** Get a contact (GET /api/v1/contacts/{id}) */
  contactsGet(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/contacts/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** Create an import (POST /api/v1/contacts/import) */
  contactsImport(input: { "rows": unknown[]; "listName"?: string; "skipExisting"?: boolean }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/contacts/import`, query, all);
  }

  /** List contacts (GET /api/v1/contacts) */
  contactsList(input?: { "cursor"?: unknown; "limit"?: unknown; "q"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["cursor"] = all["cursor"]; delete all["cursor"];
    query["limit"] = all["limit"]; delete all["limit"];
    query["q"] = all["q"]; delete all["q"];
    return this.call("GET", `/api/v1/contacts`, query, undefined);
  }

  /** Update a contact (PATCH /api/v1/contacts/{id}) */
  contactsUpdate(id: string, input?: { "email"?: string; "phone"?: string; "firstName"?: string; "lastName"?: string; "socialHandles"?: Record<string, unknown>; "subscriptions"?: Record<string, unknown>; "attributes"?: Record<string, unknown>; "source"?: string; "externalRef"?: string }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/contacts/${encodeURIComponent(id)}`, query, all);
  }

  /** Create a creator profile (POST /api/v1/creator-profile) */
  creatorProfileCreate(input: { "handle": string; "displayName": string; "bio"?: string; "avatarKey"?: string; "niches"?: unknown[]; "country"?: string; "languages"?: unknown[]; "rateCard"?: Record<string, unknown>; "rateCardModifiers"?: Record<string, unknown>; "platformLinks"?: Record<string, unknown>; "payoutMethod"?: Record<string, unknown>; "email"?: string }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/creator-profile`, query, all);
  }

  /** List me (GET /api/v1/creator-profile/me) */
  creatorProfileMe(): Promise<unknown> {
    return this.call("GET", `/api/v1/creator-profile/me`, {}, undefined);
  }

  /** Update me (PATCH /api/v1/creator-profile/me) */
  creatorProfileUpdateMe(input?: { "handle"?: string; "displayName"?: string; "bio"?: string; "avatarKey"?: string; "niches"?: unknown[]; "country"?: string; "languages"?: unknown[]; "rateCard"?: Record<string, unknown>; "rateCardModifiers"?: Record<string, unknown>; "platformLinks"?: Record<string, unknown>; "payoutMethod"?: Record<string, unknown>; "email"?: string }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/creator-profile/me`, query, all);
  }

  /** Live single-channel validation for the editor's on-blur check. (POST /api/v1/creator-profile/validate-channel) */
  creatorProfileValidateChannel(input?: { "handle"?: unknown; "platform"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/creator-profile/validate-channel`, query, all);
  }

  /** Delete a connect (DELETE /api/v1/creator-stats/connect/{platform}) */
  creatorStatsConnect(platform: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/creator-stats/connect/${encodeURIComponent(platform)}`, {}, undefined);
  }

  /** List callback (GET /api/v1/creator-stats/connect/{platform}/callback) */
  creatorStatsConnectCallback(platform: string, input?: { "code"?: unknown; "state"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["code"] = all["code"]; delete all["code"];
    query["state"] = all["state"]; delete all["state"];
    return this.call("GET", `/api/v1/creator-stats/connect/${encodeURIComponent(platform)}/callback`, query, undefined);
  }

  /** Lets the creator pick one of the linked IGs after OAuth when multiple Pages are linked. (POST /api/v1/creator-stats/connect/{platform}/select) */
  creatorStatsConnectSelect(platform: string, input?: { "igUserId"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/creator-stats/connect/${encodeURIComponent(platform)}/select`, query, all);
  }

  /** List start (GET /api/v1/creator-stats/connect/{platform}/start) */
  creatorStatsConnectStart(platform: string): Promise<unknown> {
    return this.call("GET", `/api/v1/creator-stats/connect/${encodeURIComponent(platform)}/start`, {}, undefined);
  }

  /** Get a creator stat (GET /api/v1/creator-stats/{handleOrId}) */
  creatorStatsGet(handleOrId: string): Promise<unknown> {
    return this.call("GET", `/api/v1/creator-stats/${encodeURIComponent(handleOrId)}`, {}, undefined);
  }

  /** Time-series history for the creator-stats chart (SB-style "last 30 days"). (GET /api/v1/creator-stats/{creatorId}/history) */
  creatorStatsHistory(creatorId: string, input?: { "days"?: unknown; "platform"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["days"] = all["days"]; delete all["days"];
    query["platform"] = all["platform"]; delete all["platform"];
    return this.call("GET", `/api/v1/creator-stats/${encodeURIComponent(creatorId)}/history`, query, undefined);
  }

  /** List connections (GET /api/v1/creator-stats/me/connections) */
  creatorStatsMeConnections(): Promise<unknown> {
    return this.call("GET", `/api/v1/creator-stats/me/connections`, {}, undefined);
  }

  /** Create a refresh platform (POST /api/v1/creator-stats/me/refresh-platform) */
  creatorStatsMeRefreshPlatform(input?: { "platform"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/creator-stats/me/refresh-platform`, query, all);
  }

  /** Public list for the storefront's "available codes" component. (GET /api/v1/discount-codes/applicable/{accountId}) */
  discountCodesApplicable(accountId: string, input?: { "currency"?: unknown; "productId"?: unknown; "subtotal"?: unknown; "tags"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["currency"] = all["currency"]; delete all["currency"];
    query["productId"] = all["productId"]; delete all["productId"];
    query["subtotal"] = all["subtotal"]; delete all["subtotal"];
    query["tags"] = all["tags"]; delete all["tags"];
    return this.call("GET", `/api/v1/discount-codes/applicable/${encodeURIComponent(accountId)}`, query, undefined);
  }

  /** Create a discount code (POST /api/v1/discount-codes) */
  discountCodesCreate(input: { "code": string; "description"?: string; "type": "percent" | "fixed" | "shipping_percent" | "shipping_fixed"; "value": number; "currency": string; "scope"?: "cart" | "products" | "tags"; "productIds"?: unknown[]; "tagFilter"?: unknown[]; "minPurchaseAmount"?: number; "maxUsesTotal"?: number; "maxUsesPerCustomer"?: number; "startsAt"?: string; "expiresAt"?: string; "active"?: boolean; "public"?: boolean; "marketingCampaignId"?: string }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/discount-codes`, query, all);
  }

  /** Delete a discount code (DELETE /api/v1/discount-codes/{id}) */
  discountCodesDelete(id: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/discount-codes/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** Get a discount code (GET /api/v1/discount-codes/{id}) */
  discountCodesGet(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/discount-codes/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List discount codes (GET /api/v1/discount-codes) */
  discountCodesList(input?: { "active"?: unknown; "cursor"?: unknown; "limit"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["active"] = all["active"]; delete all["active"];
    query["cursor"] = all["cursor"]; delete all["cursor"];
    query["limit"] = all["limit"]; delete all["limit"];
    return this.call("GET", `/api/v1/discount-codes`, query, undefined);
  }

  /** Commits a redemption. (POST /api/v1/discount-codes/redeem) */
  discountCodesRedeem(input: { "accountId": string; "discountCodeId": string; "checkoutSessionId": string; "customerId"?: string; "appliedAmount": number; "appliedShipping"?: number; "externalSource"?: string; "externalRef"?: string; "orderGrossIdr"?: number }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/discount-codes/redeem`, query, all);
  }

  /** Update a discount code (PATCH /api/v1/discount-codes/{id}) */
  discountCodesUpdate(id: string, input?: { "description"?: string; "type"?: "percent" | "fixed" | "shipping_percent" | "shipping_fixed"; "value"?: number; "currency"?: string; "scope"?: "cart" | "products" | "tags"; "productIds"?: unknown[]; "tagFilter"?: unknown[]; "minPurchaseAmount"?: number; "maxUsesTotal"?: number; "maxUsesPerCustomer"?: number; "startsAt"?: string; "expiresAt"?: string; "active"?: boolean; "public"?: boolean; "marketingCampaignId"?: string }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/discount-codes/${encodeURIComponent(id)}`, query, all);
  }

  /** Read-only preview. (POST /api/v1/discount-codes/validate) */
  discountCodesValidate(input: { "accountId": string; "code": string; "subtotal": number; "currency": string; "shippingCost"?: number; "customerId"?: string; "items"?: unknown[] }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/discount-codes/validate`, query, all);
  }

  /** List config (GET /api/v1/feeds/config) */
  feedsConfig(): Promise<unknown> {
    return this.call("GET", `/api/v1/feeds/config`, {}, undefined);
  }

  /** Google Merchant Center XML feed. (GET /api/v1/feeds/google/{accountId}.xml) */
  feedsGoogle(accountId: string): Promise<unknown> {
    return this.call("GET", `/api/v1/feeds/google/${encodeURIComponent(accountId)}.xml`, {}, undefined);
  }

  /** Update config (PATCH /api/v1/feeds/config) */
  feedsUpdateConfig(input?: { "enabled"?: boolean; "defaultGoogleProductCategory"?: string; "includeUnpublished"?: boolean; "marketingCampaignId"?: string }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/feeds/config`, query, all);
  }

  /** List analytics (GET /api/v1/funnels/{id}/analytics) */
  funnelsAnalytics(id: string, input?: { "since"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["since"] = all["since"]; delete all["since"];
    return this.call("GET", `/api/v1/funnels/${encodeURIComponent(id)}/analytics`, query, undefined);
  }

  /** Create a funnel (POST /api/v1/funnels) */
  funnelsCreate(input: { "name": string; "description"?: string; "triggerKind": "list_added" | "tag_added" | "signup_form" | "abandoned_cart" | "manual_add" | "webhook_event"; "triggerConfig"?: Record<string, unknown>; "status"?: "draft" | "active" | "paused" | "archived"; "steps"?: unknown[] }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/funnels`, query, all);
  }

  /** Delete a funnel (DELETE /api/v1/funnels/{id}) */
  funnelsDelete(id: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/funnels/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** Enroll a funnel (POST /api/v1/funnels/{id}/enroll) */
  funnelsEnroll(id: string, input: { "contactIds": unknown[] }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/funnels/${encodeURIComponent(id)}/enroll`, query, all);
  }

  /** List enrollments (GET /api/v1/funnels/{id}/enrollments) */
  funnelsEnrollments(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/funnels/${encodeURIComponent(id)}/enrollments`, {}, undefined);
  }

  /** Get a funnel (GET /api/v1/funnels/{id}) */
  funnelsGet(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/funnels/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List funnels (GET /api/v1/funnels) */
  funnelsList(): Promise<unknown> {
    return this.call("GET", `/api/v1/funnels`, {}, undefined);
  }

  /** Steps a funnel (PUT /api/v1/funnels/{id}/steps) */
  funnelsSteps(id: string, input: { "steps": unknown[] }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PUT", `/api/v1/funnels/${encodeURIComponent(id)}/steps`, query, all);
  }

  /** Update a funnel (PATCH /api/v1/funnels/{id}) */
  funnelsUpdate(id: string, input?: { "name"?: string; "description"?: string; "triggerKind"?: "list_added" | "tag_added" | "signup_form" | "abandoned_cart" | "manual_add" | "webhook_event"; "triggerConfig"?: Record<string, unknown>; "status"?: "draft" | "active" | "paused" | "archived"; "steps"?: unknown[] }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/funnels/${encodeURIComponent(id)}`, query, all);
  }

  /** Archive an inbox (POST /api/v1/inbox/{id}/archive) */
  inboxArchive(id: string): Promise<unknown> {
    return this.call("POST", `/api/v1/inbox/${encodeURIComponent(id)}/archive`, {}, undefined);
  }

  /** Read an inbox (POST /api/v1/inbox/{id}/read) */
  inboxRead(id: string): Promise<unknown> {
    return this.call("POST", `/api/v1/inbox/${encodeURIComponent(id)}/read`, {}, undefined);
  }

  /** List threads (GET /api/v1/inbox/threads) */
  inboxThreads(): Promise<unknown> {
    return this.call("GET", `/api/v1/inbox/threads`, {}, undefined);
  }

  /** Get a thread (GET /api/v1/inbox/threads/{provider}/{handle}) */
  inboxThreads2(provider: string, handle: string): Promise<unknown> {
    return this.call("GET", `/api/v1/inbox/threads/${encodeURIComponent(provider)}/${encodeURIComponent(handle)}`, {}, undefined);
  }

  /** Get a campaign (GET /api/v1/insights/campaigns/{id}) */
  insightsCampaigns(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/insights/campaigns/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List commissions trend (GET /api/v1/insights/commissions-trend) */
  insightsCommissionsTrend(input?: { "days"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["days"] = all["days"]; delete all["days"];
    return this.call("GET", `/api/v1/insights/commissions-trend`, query, undefined);
  }

  /** List overview (GET /api/v1/insights/overview) */
  insightsOverview(): Promise<unknown> {
    return this.call("GET", `/api/v1/insights/overview`, {}, undefined);
  }

  /** Get a program (GET /api/v1/insights/programs/{id}) */
  insightsPrograms(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/insights/programs/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List email (GET /api/v1/integrations/email) */
  integrationsEmail(): Promise<unknown> {
    return this.call("GET", `/api/v1/integrations/email`, {}, undefined);
  }

  /** Set email (PUT /api/v1/integrations/email) */
  integrationsSetEmail(input?: { "provider"?: "resend"; "apiKey"?: string; "fromEmail"?: string; "fromName"?: string; "active"?: boolean }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PUT", `/api/v1/integrations/email`, query, all);
  }

  /** List status (GET /api/v1/integrations/status) */
  integrationsStatus(): Promise<unknown> {
    return this.call("GET", `/api/v1/integrations/status`, {}, undefined);
  }

  /** Create a kyc (POST /api/v1/kyc) */
  kycCreate(input: { "idType": "ktp" | "passport" | "driver_license"; "idNumber": string; "idImageKey": string; "selfieImageKey"?: string }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/kyc`, query, all);
  }

  /** List me (GET /api/v1/kyc/me) */
  kycMe(): Promise<unknown> {
    return this.call("GET", `/api/v1/kyc/me`, {}, undefined);
  }

  /** Create an earn (POST /api/v1/loyalty/earn) */
  loyaltyEarn(input: { "customerId": string; "orderGrossIdr": number; "externalSource"?: string; "externalRef"?: string; "checkoutSessionId"?: string; "orderId"?: string }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/loyalty/earn`, query, all);
  }

  /** List balance (GET /api/v1/loyalty/members/{customerId}/balance) */
  loyaltyMembersBalance(customerId: string): Promise<unknown> {
    return this.call("GET", `/api/v1/loyalty/members/${encodeURIComponent(customerId)}/balance`, {}, undefined);
  }

  /** List history (GET /api/v1/loyalty/members/{customerId}/history) */
  loyaltyMembersHistory(customerId: string, input?: { "limit"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["limit"] = all["limit"]; delete all["limit"];
    return this.call("GET", `/api/v1/loyalty/members/${encodeURIComponent(customerId)}/history`, query, undefined);
  }

  /** List program (GET /api/v1/loyalty/program) */
  loyaltyProgram(): Promise<unknown> {
    return this.call("GET", `/api/v1/loyalty/program`, {}, undefined);
  }

  /** Create a redeem (POST /api/v1/loyalty/redeem) */
  loyaltyRedeem(input: { "customerId": string; "points": number; "externalSource"?: string; "externalRef"?: string; "checkoutSessionId"?: string; "orderId"?: string }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/loyalty/redeem`, query, all);
  }

  /** Set program (PUT /api/v1/loyalty/program) */
  loyaltySetProgram(input: { "enabled"?: boolean; "earnRatePoints": number; "redeemValueIdr": number; "marketingCampaignId"?: string }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PUT", `/api/v1/loyalty/program`, query, all);
  }

  /** Create a void (POST /api/v1/loyalty/void) */
  loyaltyVoid(input: { "externalRef": string; "externalSource"?: string }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/loyalty/void`, query, all);
  }

  /** Convenience endpoint for "Tie to campaign" dropdowns across the portal: filtered to non-archived campaigns, lightweight shape, no counts. (GET /api/v1/marketing-campaigns/_/selector) */
  marketingCampaignsSelector(): Promise<unknown> {
    return this.call("GET", `/api/v1/marketing-campaigns/_/selector`, {}, undefined);
  }

  /** Create a marketing campaign (POST /api/v1/marketing-campaigns) */
  marketingCampaignsCreate(input: { "name": string; "description"?: string; "goal"?: "awareness" | "conversion" | "retention" | "launch" | "other"; "status"?: "draft" | "live" | "paused" | "completed" | "archived"; "budgetIdr"?: number; "startsAt"?: string; "endsAt"?: string; "notes"?: string }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/marketing-campaigns`, query, all);
  }

  /** Soft-delete: status='archived'. (DELETE /api/v1/marketing-campaigns/{id}) */
  marketingCampaignsDelete(id: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/marketing-campaigns/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List full (GET /api/v1/marketing-campaigns/{id}/full) */
  marketingCampaignsFull(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/marketing-campaigns/${encodeURIComponent(id)}/full`, {}, undefined);
  }

  /** Get a marketing campaign (GET /api/v1/marketing-campaigns/{id}) */
  marketingCampaignsGet(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/marketing-campaigns/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List marketing campaigns (GET /api/v1/marketing-campaigns) */
  marketingCampaignsList(input?: { "status"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["status"] = all["status"]; delete all["status"];
    return this.call("GET", `/api/v1/marketing-campaigns`, query, undefined);
  }

  /** Update a marketing campaign (PATCH /api/v1/marketing-campaigns/{id}) */
  marketingCampaignsUpdate(id: string, input?: { "name"?: string; "description"?: string; "goal"?: "awareness" | "conversion" | "retention" | "launch" | "other"; "status"?: "draft" | "live" | "paused" | "completed" | "archived"; "budgetIdr"?: number; "startsAt"?: string; "endsAt"?: string; "notes"?: string }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/marketing-campaigns/${encodeURIComponent(id)}`, query, all);
  }

  /** List campaigns (GET /api/v1/marketplace/campaigns) */
  marketplaceCampaigns(input?: { "cursor"?: unknown; "limit"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["cursor"] = all["cursor"]; delete all["cursor"];
    query["limit"] = all["limit"]; delete all["limit"];
    return this.call("GET", `/api/v1/marketplace/campaigns`, query, undefined);
  }

  /** Get a campaign (GET /api/v1/marketplace/campaigns/{id}) */
  marketplaceCampaigns2(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/marketplace/campaigns/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** Apply a campaign (POST /api/v1/marketplace/campaigns/{id}/apply) */
  marketplaceCampaignsApply(id: string, input: { "pitchText": string; "proposedRate"?: number }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/marketplace/campaigns/${encodeURIComponent(id)}/apply`, query, all);
  }

  /** List creators (GET /api/v1/marketplace/creators) */
  marketplaceCreators(input?: { "niche"?: string; "country"?: string; "language"?: string; "cursor"?: string; "limit"?: number }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["niche"] = all["niche"]; delete all["niche"];
    query["country"] = all["country"]; delete all["country"];
    query["language"] = all["language"]; delete all["language"];
    query["cursor"] = all["cursor"]; delete all["cursor"];
    query["limit"] = all["limit"]; delete all["limit"];
    return this.call("GET", `/api/v1/marketplace/creators`, query, undefined);
  }

  /** Get a creator (GET /api/v1/marketplace/creators/{handle}) */
  marketplaceCreators2(handle: string): Promise<unknown> {
    return this.call("GET", `/api/v1/marketplace/creators/${encodeURIComponent(handle)}`, {}, undefined);
  }

  /** List applications (GET /api/v1/marketplace/me/applications) */
  marketplaceMeApplications(): Promise<unknown> {
    return this.call("GET", `/api/v1/marketplace/me/applications`, {}, undefined);
  }

  /** List invitations (GET /api/v1/marketplace/me/invitations) */
  marketplaceMeInvitations(): Promise<unknown> {
    return this.call("GET", `/api/v1/marketplace/me/invitations`, {}, undefined);
  }

  /** Respond an invitation (POST /api/v1/marketplace/me/invitations/{invId}/respond) */
  marketplaceMeInvitationsRespond(invId: string, input: { "accept": boolean }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/marketplace/me/invitations/${encodeURIComponent(invId)}/respond`, query, all);
  }

  /** Get a merchant (GET /api/v1/merchants/{slug}) */
  merchantsGet(slug: string): Promise<unknown> {
    return this.call("GET", `/api/v1/merchants/${encodeURIComponent(slug)}`, {}, undefined);
  }

  /** List merchants (GET /api/v1/merchants) */
  merchantsList(): Promise<unknown> {
    return this.call("GET", `/api/v1/merchants`, {}, undefined);
  }

  /** List me (GET /api/v1/merchants/me) */
  merchantsMe(): Promise<unknown> {
    return this.call("GET", `/api/v1/merchants/me`, {}, undefined);
  }

  /** Create a publish (POST /api/v1/merchants/me/publish) */
  merchantsMePublish(): Promise<unknown> {
    return this.call("POST", `/api/v1/merchants/me/publish`, {}, undefined);
  }

  /** Create an unpublish (POST /api/v1/merchants/me/unpublish) */
  merchantsMeUnpublish(): Promise<unknown> {
    return this.call("POST", `/api/v1/merchants/me/unpublish`, {}, undefined);
  }

  /** Set me (PUT /api/v1/merchants/me) */
  merchantsSetMe(input: { "brandName": string; "bio"?: string; "logoKey"?: string; "socialLinks"?: Record<string, unknown> }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PUT", `/api/v1/merchants/me`, query, all);
  }

  /** List pixels (GET /api/v1/pixels) */
  pixelsList(): Promise<unknown> {
    return this.call("GET", `/api/v1/pixels`, {}, undefined);
  }

  /** Public read — storefront-facing. (GET /api/v1/pixels/public/{accountId}) */
  pixelsPublic(accountId: string): Promise<unknown> {
    return this.call("GET", `/api/v1/pixels/public/${encodeURIComponent(accountId)}`, {}, undefined);
  }

  /** Update pixels (PATCH /api/v1/pixels) */
  pixelsUpdate(input?: { "metaPixelId"?: string; "metaCapiAccessToken"?: string; "metaTestEventCode"?: string; "googleAnalyticsId"?: string; "googleAdsConversionId"?: string; "googleAdsPurchaseLabel"?: string; "tiktokPixelId"?: string; "enabled"?: boolean }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/pixels`, query, all);
  }

  /** The affiliator side reads /affiliates/me/commissions. (GET /api/v1/programs/{id}/commissions) */
  programsCommissions(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/programs/${encodeURIComponent(id)}/commissions`, {}, undefined);
  }

  /** List commissions (GET /api/v1/programs/commissions) */
  programsCommissions2(input?: { "status"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["status"] = all["status"]; delete all["status"];
    return this.call("GET", `/api/v1/programs/commissions`, query, undefined);
  }

  /** Approve a commission (POST /api/v1/programs/{id}/commissions/{cid}/approve) */
  programsCommissionsApprove(id: string, cid: string): Promise<unknown> {
    return this.call("POST", `/api/v1/programs/${encodeURIComponent(id)}/commissions/${encodeURIComponent(cid)}/approve`, {}, undefined);
  }

  /** Void a commission (POST /api/v1/programs/{id}/commissions/{cid}/void) */
  programsCommissionsVoid(id: string, cid: string, input?: { "reason"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/programs/${encodeURIComponent(id)}/commissions/${encodeURIComponent(cid)}/void`, query, all);
  }

  /** Create a program (POST /api/v1/programs) */
  programsCreate(input: { "name": string; "description"?: string; "terms"?: string; "targetUrl"?: string; "commissionModel"?: "perf_redemption" | "perf_sale" | "tiered"; "commissionRate"?: number; "cookieDays"?: number; "status"?: "draft" | "open" | "paused" | "closed"; "autoApprove"?: boolean; "minFollowerCount"?: number; "requiredAudienceCountries"?: unknown[]; "requiresKyc"?: boolean; "tierFloor"?: "starter" | "growth" | "scale"; "platformFeeRate"?: number; "marketingCampaignId"?: string }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/programs`, query, all);
  }

  /** Delete a program (DELETE /api/v1/programs/{id}) */
  programsDelete(id: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/programs/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List enrollments (GET /api/v1/programs/{id}/enrollments) */
  programsEnrollments(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/programs/${encodeURIComponent(id)}/enrollments`, {}, undefined);
  }

  /** Approve an enrollment (POST /api/v1/programs/{id}/enrollments/{eid}/approve) */
  programsEnrollmentsApprove(id: string, eid: string): Promise<unknown> {
    return this.call("POST", `/api/v1/programs/${encodeURIComponent(id)}/enrollments/${encodeURIComponent(eid)}/approve`, {}, undefined);
  }

  /** Reject an enrollment (POST /api/v1/programs/{id}/enrollments/{eid}/reject) */
  programsEnrollmentsReject(id: string, eid: string, input?: { "reason"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/programs/${encodeURIComponent(id)}/enrollments/${encodeURIComponent(eid)}/reject`, query, all);
  }

  /** Revoke an enrollment (POST /api/v1/programs/{id}/enrollments/{eid}/revoke) */
  programsEnrollmentsRevoke(id: string, eid: string, input?: { "reason"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/programs/${encodeURIComponent(id)}/enrollments/${encodeURIComponent(eid)}/revoke`, query, all);
  }

  /** Get a program (GET /api/v1/programs/{id}) */
  programsGet(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/programs/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List programs (GET /api/v1/programs) */
  programsList(): Promise<unknown> {
    return this.call("GET", `/api/v1/programs`, {}, undefined);
  }

  /** Update a program (PATCH /api/v1/programs/{id}) */
  programsUpdate(id: string, input?: { "name"?: string; "description"?: string; "terms"?: string; "targetUrl"?: string; "commissionModel"?: "perf_redemption" | "perf_sale" | "tiered"; "commissionRate"?: number; "cookieDays"?: number; "status"?: "draft" | "open" | "paused" | "closed"; "autoApprove"?: boolean; "minFollowerCount"?: number; "requiredAudienceCountries"?: unknown[]; "requiresKyc"?: boolean; "tierFloor"?: "starter" | "growth" | "scale"; "platformFeeRate"?: number; "marketingCampaignId"?: string }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/programs/${encodeURIComponent(id)}`, query, all);
  }

  /** Create a checkout start (POST /api/v1/referrals/attributions/checkout-start) */
  referralsAttributionsCheckoutStart(input: { "accountId": string; "customerId": string; "checkoutSessionId": string }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/referrals/attributions/checkout-start`, query, all);
  }

  /** Create a fulfill (POST /api/v1/referrals/attributions/fulfill) */
  referralsAttributionsFulfill(input: { "checkoutSessionId": string; "status": string; "currency": string; "amount": number }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/referrals/attributions/fulfill`, query, all);
  }

  /** Create a void (POST /api/v1/referrals/attributions/void) */
  referralsAttributionsVoid(input: { "checkoutSessionId": string }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/referrals/attributions/void`, query, all);
  }

  /** Get a link (GET /api/v1/referrals/links/{accountId}/{code}) */
  referralsLinks(accountId: string, code: string): Promise<unknown> {
    return this.call("GET", `/api/v1/referrals/links/${encodeURIComponent(accountId)}/${encodeURIComponent(code)}`, {}, undefined);
  }

  /** Create a click (POST /api/v1/referrals/links/click) */
  referralsLinksClick(input: { "accountId": string; "code": string }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/referrals/links/click`, query, all);
  }

  /** Create an issue (POST /api/v1/referrals/links/issue) */
  referralsLinksIssue(input: { "accountId": string; "customerId": string }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/referrals/links/issue`, query, all);
  }

  /** List program (GET /api/v1/referrals/program) */
  referralsProgram(): Promise<unknown> {
    return this.call("GET", `/api/v1/referrals/program`, {}, undefined);
  }

  /** Get a reward (GET /api/v1/referrals/rewards/{accountId}/{customerId}) */
  referralsRewards(accountId: string, customerId: string): Promise<unknown> {
    return this.call("GET", `/api/v1/referrals/rewards/${encodeURIComponent(accountId)}/${encodeURIComponent(customerId)}`, {}, undefined);
  }

  /** Set program (PUT /api/v1/referrals/program) */
  referralsSetProgram(input: { "enabled"?: boolean; "rewardType": "percent" | "fixed" | "shipping_percent" | "shipping_fixed"; "referrerValue": number; "refereeValue": number; "currency": string; "minPurchaseAmount"?: number; "rewardExpiryDays"?: number; "attributionWindowDays"?: number; "maxRewardsPerReferrer"?: number; "programTerms"?: string; "marketingCampaignId"?: string }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PUT", `/api/v1/referrals/program`, query, all);
  }

  /** List stats (GET /api/v1/referrals/stats) */
  referralsStats(): Promise<unknown> {
    return this.call("GET", `/api/v1/referrals/stats`, {}, undefined);
  }

  /** List avatar (GET /api/v1/uploads/avatar) */
  uploadsAvatar(input?: { "key"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["key"] = all["key"]; delete all["key"];
    return this.call("GET", `/api/v1/uploads/avatar`, query, undefined);
  }

  /** Signed-GET for a deliverable asset. (GET /api/v1/uploads/deliverable) */
  uploadsDeliverable(input?: { "id"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["id"] = all["id"]; delete all["id"];
    return this.call("GET", `/api/v1/uploads/deliverable`, query, undefined);
  }

  /** Create a from run media (POST /api/v1/uploads/from-run-media) */
  uploadsFromRunMedia(input?: { "filename"?: unknown; "runId"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/uploads/from-run-media`, query, all);
  }

  /** Url { url } Re-host a public image onto our own storage and return the durable URL. (POST /api/v1/uploads/from-url) */
  uploadsFromUrl(input?: { "url"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/uploads/from-url`, query, all);
  }

  /** Signed-GET for merchant-owned assets. (GET /api/v1/uploads/merchant-asset) */
  uploadsMerchantAsset(input?: { "key"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["key"] = all["key"]; delete all["key"];
    return this.call("GET", `/api/v1/uploads/merchant-asset`, query, undefined);
  }

  /** Create a sign (POST /api/v1/uploads/sign) */
  uploadsSign(input: { "kind": "kyc-id" | "kyc-selfie" | "profile-avatar" | "deliverable-asset" | "compose-asset" | "merchant-logo"; "contentType": "image/jpeg" | "image/png" | "image/webp" | "image/heic" | "video/mp4" | "video/quicktime" | "video/webm"; "collaborationId"?: string; "deliverableId"?: string }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/uploads/sign`, query, all);
  }

  /** Merchant-side asset upload. (POST /api/v1/uploads/sign-merchant) */
  uploadsSignMerchant(input: { "kind": "kyc-id" | "kyc-selfie" | "profile-avatar" | "deliverable-asset" | "compose-asset" | "merchant-logo"; "contentType": "image/jpeg" | "image/png" | "image/webp" | "image/heic" | "video/mp4" | "video/quicktime" | "video/webm"; "collaborationId"?: string; "deliverableId"?: string }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/uploads/sign-merchant`, query, all);
  }

  /** Create an endpoint (POST /api/v1/webhooks/endpoints) */
  webhooksCreateEndpoints(input: { "url": string; "events"?: unknown[]; "description"?: string }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/webhooks/endpoints`, query, all);
  }

  /** Delete an endpoint (DELETE /api/v1/webhooks/endpoints/{id}) */
  webhooksDeleteEndpoints(id: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/webhooks/endpoints/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List endpoints (GET /api/v1/webhooks/endpoints) */
  webhooksEndpoints(): Promise<unknown> {
    return this.call("GET", `/api/v1/webhooks/endpoints`, {}, undefined);
  }

  /** The three SDKs (`listEvents({ limit, cursor, type })` in node, python and go) and the dashboard call site have promised these params since they shipped; the server took none of them — a fixed `take: 5 (GET /api/v1/webhooks/events) */
  webhooksEvents(input?: { "cursor"?: unknown; "limit"?: unknown; "type"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["cursor"] = all["cursor"]; delete all["cursor"];
    query["limit"] = all["limit"]; delete all["limit"];
    query["type"] = all["type"]; delete all["type"];
    return this.call("GET", `/api/v1/webhooks/events`, query, undefined);
  }

  /** Update an endpoint (PATCH /api/v1/webhooks/endpoints/{id}) */
  webhooksUpdateEndpoints(id: string): Promise<unknown> {
    return this.call("PATCH", `/api/v1/webhooks/endpoints/${encodeURIComponent(id)}`, {}, undefined);
  }
}
